/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /*
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  */

  // But you can create a sidebar manually
  generalSidebar: [
    'welcome',
    'quick-start',
  ],
  epitopeSidebar: [
    'EpitopeID/epitopeid',
    'EpitopeID/input',
    {
      type: 'category',
      label: 'Reference Database (-d)',
      link: {type: 'doc', id: "EpitopeID/db/structure"},
      items: [
        'EpitopeID/db/pregenerated',
        'EpitopeID/db/custom-db'
      ]
    },
    'EpitopeID/output',
    'EpitopeID/performance',
    'EpitopeID/threshold',
    'EpitopeID/faq',
  ],
  deletionSidebar: [
    'DeletionID/deletionid',
    'DeletionID/input',
    {
      type: 'category',
      label: 'Reference Database (-d)',
      link: {type: 'doc', id: "DeletionID/db/structure"},
      items: [
        'DeletionID/db/pregenerated',
        'DeletionID/db/custom-db'
      ]
    },
    'DeletionID/output',
    'DeletionID/faq',
  ],
  strainSidebar: [
    'StrainID/strainid',
    'StrainID/input',
    'StrainID/genome',
    {
      type: 'category',
      label: 'Reference Database (-v)',
      link: {type: 'doc', id: "StrainID/db/structure"},
      items: [
        'StrainID/db/pregenerated',
        'StrainID/db/custom-db'
      ]
    },
    'StrainID/output',
    'StrainID/seed',
    'StrainID/faq',
  ],
};

module.exports = sidebars;
